[package]
name = "opensource-contentauthenticity-org"
version = "0.1.0"

[dependencies]
c2pa = { git = "https://github.com/contentauth/c2pa-rs", branch = "main" }
c2patool = { git = "https://github.com/contentauth/c2patool", branch = "main" }
