name: Build and deploy to Netlify
on:
  push:
  pull_request:
    types: [opened]
jobs:
  build-deploy:
    name: Build and deploy to Netlify
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: site
    steps:
      - name: Checkout c2pa
        uses: actions/checkout@v3
        with:
          path: c2pa
      - name: Checkout site
        uses: actions/checkout@v3
        with:
          path: site
      - name: Install dependencies
        run: npm install
      - name: Build site
        run: npm run build
      - name: Generate API docs
        run: npm run generate-api-docs
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './site/build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
